### ISSUE TITLE
function AwesomeChat.Storage.start_link/0 is undefined or private

### ISSUE THREAD

**Issue by tomasvts** [bodymindarts/awesomechat-elixir#1]
I'm learning Elixir and was curious about your project. Unfortunately I can't compile it because it fails when I try to start the phoenix server:

```
Generated awesomechat app
[info] Running AwesomeChat.Endpoint with Cowboy on port 4000 (http)
[info] Application awesomechat exited: AwesomeChat.start(:normal, []) returned an error: shutdown: failed to start child: AwesomeChat.Storage
    ** (EXIT) an exception was raised:
        ** (UndefinedFunctionError) function AwesomeChat.Storage.start_link/0 is undefined or private. Did you mean one of:

      * start_link/2

            (awesomechat) AwesomeChat.Storage.start_link()
            (stdlib) supervisor.erl:358: :supervisor.do_start_child/2
            (stdlib) supervisor.erl:341: :supervisor.start_children/3
            (stdlib) supervisor.erl:307: :supervisor.init_children/2
            (stdlib) gen_server.erl:328: :gen_server.init_it/6
            (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
[info] Application poolboy exited: :stopped
[info] Application cowboy exited: :stopped
[info] Application cowlib exited: :stopped
[info] Application ranch exited: :stopped
[info] Application phoenix_html exited: :stopped

=INFO REPORT==== 29-Jun-2016::00:21:03 ===
    application: logger
    exited: stopped
    type: temporary
** (Mix) Could not start application awesomechat: AwesomeChat.start(:normal, []) returned an error: shutdown: failed to start child: AwesomeChat.Storage
    ** (EXIT) an exception was raised:
        ** (UndefinedFunctionError) function AwesomeChat.Storage.start_link/0 is undefined or private. Did you mean one of:

      * start_link/2

            (awesomechat) AwesomeChat.Storage.start_link()
            (stdlib) supervisor.erl:358: :supervisor.do_start_child/2
            (stdlib) supervisor.erl:341: :supervisor.start_children/3
            (stdlib) supervisor.erl:307: :supervisor.init_children/2
            (stdlib) gen_server.erl:328: :gen_server.init_it/6
            (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
```

I don't know what is going on :(

More info:
OS: MacOS Capitan 10.11.3
elixir -v: 

```
Erlang/OTP 18 [erts-7.3] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]
Elixir 1.3.0
```

What I have done:

> git clone https://github.com/bodymindarts/awesomechat-elixir.git
> cd awesomechat-elixir/
> npm install && mix deps.get
> brew install redis
> (open new console)  redis-server /usr/local/etc/redis.conf
> mix phoenix.server
> ???
> _explodes_

**Comment by bodymindarts** [comment]
Hi @tomasvts,

cool that you found this project.
I wrote this little app to learn elixir and phoenix about 1 year ago on an old version of elixir (v1.0.4) and there have been some slight syntactic changes to the language since then which explains the error you encountered.

I have got it to work again now and hope it will help you learn. `git pull` in the latest changes and re-run `npm install && mix deps.get` to see if it works now.

To experiment with what this app can do:
- Open 2 different browsers (eg chrome + safari) and point them both to `localhost:4000`.
- Login and do some chatting
- Turn the server off and do some more chatting
- Turn it back on and see the historys sync up
- You can also stop and start the database while chatting and see it sync up again too, so in general its built for resilience.
